-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 14:39:02 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accommodation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `accommodation` ;

-- -----------------------------------------------------
-- Schema accommodation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accommodation` DEFAULT CHARACTER SET utf8 ;
USE `accommodation` ;

-- -----------------------------------------------------
-- Table `accommodation`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accommodation`.`users` ;

CREATE TABLE IF NOT EXISTS `accommodation`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `mobile` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accommodation`.`property_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accommodation`.`property_type` ;

CREATE TABLE IF NOT EXISTS `accommodation`.`property_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accommodation`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accommodation`.`address` ;

CREATE TABLE IF NOT EXISTS `accommodation`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NOT NULL,
  `locality` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accommodation`.`listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accommodation`.`listings` ;

CREATE TABLE IF NOT EXISTS `accommodation`.`listings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NULL,
  `Title` VARCHAR(100) NOT NULL,
  `address_id` INT NOT NULL,
  `property_id` INT NOT NULL,
  `price` INT NOT NULL,
  `availability_rooms` INT NULL,
  `possesion_date` DATETIME NULL,
  `posted_on` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `address_id_idx` (`address_id` ASC),
  INDEX `property_id_idx` (`property_id` ASC),
  INDEX `users_id_idx` (`users_id` ASC),
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `accommodation`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `property_id`
    FOREIGN KEY (`property_id`)
    REFERENCES `accommodation`.`property_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `accommodation`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accommodation`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accommodation`.`images` ;

CREATE TABLE IF NOT EXISTS `accommodation`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listings_id` INT NOT NULL,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `listings_id_idx` (`listings_id` ASC),
  CONSTRAINT `listings_id`
    FOREIGN KEY (`listings_id`)
    REFERENCES `accommodation`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
